export class ForecastModel {


    cloudBaseAvg: any
    cloudBaseMax: any
    cloudBaseMin: any
    cloudCeilingAvg: any
    cloudCeilingMax: any
    cloudCeilingMin: any
    cloudCoverAvg: any
    cloudCoverMax: any
    cloudCoverMin: any
    dewPointAvg: any
    dewPointMax: any
    dewPointMin: any
    evapotranspirationAvg: any
    evapotranspirationMax: any
    evapotranspirationMin: any
    evapotranspirationSum: any
    freezingRainIntensityAvg: any
    freezingRainIntensityMax: any
    freezingRainIntensityMin: any
    humidityAvg: any
    humidityMax: any
    humidityMin: any
    iceAccumulationAvg: any
    iceAccumulationLweAvg: any
    iceAccumulationLweMax: any
    iceAccumulationLweMin: any
    iceAccumulationLweSum: any
    iceAccumulationMax: any
    iceAccumulationMin: any
    iceAccumulationSum: any
    moonriseTime: any
    moonsetTime: any
    precipitationProbabilityAvg: any
    precipitationProbabilityMax: any
    precipitationProbabilityMin: any
    pressureSurfaceLevelAvg: any
    pressureSurfaceLevelMax: any
    pressureSurfaceLevelMin: any
    rainAccumulationAvg: any
    rainAccumulationLweAvg: any
    rainAccumulationLweMax: any
    rainAccumulationLweMin: any
    rainAccumulationMax: any
    rainAccumulationMin: any
    rainAccumulationSum: any
    rainIntensityAvg: any
    rainIntensityMax: any
    rainIntensityMin: any
    sleetAccumulationAvg: any
    sleetAccumulationLweAvg: any
    sleetAccumulationLweMax: any
    sleetAccumulationLweMin: any
    sleetAccumulationLweSum: any
    sleetAccumulationMax: any
    sleetAccumulationMin: any
    sleetIntensityAvg: any
    sleetIntensityMax: any
    sleetIntensityMin: any
    snowAccumulationAvg: any
    snowAccumulationLweAvg: any
    snowAccumulationLweMax: any
    snowAccumulationLweMin: any
    snowAccumulationLweSum: any
    snowAccumulationMax: any
    snowAccumulationMin: any
    snowAccumulationSum: any
    snowIntensityAvg: any
    snowIntensityMax: any
    snowIntensityMin: any
    sunriseTime: any
    sunsetTime: any
    temperatureApparentAvg: any
    temperatureApparentMax: any
    temperatureApparentMin: any
    temperatureAvg: any
    temperatureMax: any
    temperatureMin: any
    uvHealthConcernAvg: any
    uvHealthConcernMax: any
    uvHealthConcernMin: any
    uvIndexAvg: any
    uvIndexMax: any
    uvIndexMin: any
    visibilityAvg: any
    visibilityMax: any
    visibilityMin: any
    weatherCodeMax: any
    weatherCodeMin: any
    windDirectionAvg: any
    windGustAvg: any
    windGustMax: any
    windGustMin: any
    windSpeedAvg: any
    windSpeedMax: any
    windSpeedMin: any
}